name: tus_client
description: A tus client for dart allowing resumable uploads.
version: 0.0.1
author: Joseph N. Mutumi
homepage: https://github.com/jjmutumi/tus_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

